[project]
name = "aws13th-social-backend-gpffh20"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "ruff>=0.14.11",
    "uvicorn[standard]>=0.40.0",
]
